errormsgs = ["Oh no..",
    "I did an oopsie.",
    "Was it my fault?",
    "Wait what?",
    "Senpai, no!",
    "Wh-what happened?",
    "Fix me, master!",
    "I want to die.",
    "Critical Linux kernel error, rebooting..",
    "Error! Error!",
    "Instructions unclear, there's a hammer in my eye.",
    "I'm dead inside.",
    "Oh noes!",
    "I don't feel like it.",
    "Oh boy, it's time to ban someone!",
    "S-senpai, that syntax is way t-too big!",
    "B-baka!",
    "Error 609, committing suicide.",
    "Error machine broke"]

shipcomments = ["Oh wow, you two are just made for eachother. You should definitely meet up! :two_hearts::sparkling_heart:",
    "Wow, you seem to fit very well together! Maybe you could meet up some time? :two_hearts::sparkling_heart:",
    "I've never seen such a neat couple! :two_hearts::sparkling_heart:",
    "Oh yes, that's a good ship. :sparkling_heart:",
    "Oh wow, that's a really fucking nice ship! :sparkling_heart:",
    "Yeah, this could definitely work! Good luck with your ship! :sparkling_heart:",
    "Neat, you two seem to really like eachother. This ship could last for a while! :heart:",
    "Yeah, that's not too bad. The ship could actually work. :heart:",
    "Meh, I'm not too sure about the ship. Good luck, I guess? :heart:",
    "Good luck with your ship, you'll need a lot of it. :heart:",
    "Eh.. Good ship. :heart:"]

pokemons = ["Bulbasaur", "Ivysaur", "Venusaur", "Charmander", "Charmeleon", "Charizard", "Squirtle", "Wartortle", "Blastoise",
    "Caterpie", "Metapod", "Butterfree", "Weedle", "Kakuna", "Beedrill", "Pidgey", "Pidgiotto", "Pidgeot", "Ratatta", "Raticate",
    "Spearow", "Fearow", "Ekans", "Arbok", "Pikachu", "Raichu", "Sandshrew", "Sandslash", "Nidoran♀", "Nidorina", "Nidoqueen",
    "Nidoran♂", "Nidorino", "Nidoking", "Celfairy", "Clefable", "Vulpix", "Ninetales", "Jigglypuff", "Wigglytuff", "Zubat", "Golbat",
    "Oddish", "Gloom", "Vileplume", "Paras", "Parasect", "Venonat", "Venomoth", "Diglett", "Dugtrio", "Meowth", "Persian", "Psyduck",
    "Golduck", "Mankey", "Primeape", "Growlithe", "Arcanine", "Poliwag", "Poliwhril", "Poliwrath", "Abra", "Kadabra", "Alakazam",
    "Machop", "Machoke", "Machamp", "Bellsprout", "Weepinbell", "Victreebel", "Tentacool", "Tentacruel", "Geodude", "Graveler", "Golem",
    "Ponyta", "Rapidash", "Slowpoke", "Slowbro", "Magnemite", "Magneton", "Farfetch’d", "Doduo", "Dodrio", "Seel", "Dewgong", "Grimer",
    "Muk", "Shellder", "Cloyster", "Gastly", "Haunter", "Gengar", "Onix", "Drowzee", "Hypno", "Krabby", "Kingler", "Voltorb",
    "Electrode", "Exeggcute", "Exeggutor", "Cubone", "Marrowak", "Hitmonlee", "Hitmonchan", "Lickitung", "Koffing", "Weezing", "Rhyhorn",
    "Rhydon", "Chansey", "Tangela", "Kangaskhan", "Horsea", "Seadra", "Goldeen", "Seaking", "Staryu", "Starmie", "Mr. Mime",
    "Scyther", "Jynx", "Electabuzz", "Magmar", "Pinsir", "Tauros", "Magikarp", "Gyarados", "Lapras", "Ditto", "Eevee",
    "Vaporeon", "Jolteon", "Flareon", "Porygon", "Omanyte", "Omastar", "Kabuto", "Kabutops", "Aerodactyl", "Snorlax", "Articuno",
    "Zapdos", "Moltres", "Dratini", "Dragonair", "Dragonite", "Mewtwo", "Mew", "Chikorita", "Bayleef", "Meganium", "Cyndaquil",
    "Quilava", "Typhlosion", "Totodile", "Croconaw", "Feraligatr", "Sentret", "Furret", "Hoothoot", "Noctowl", "Ledyba", "Ledian",
    "Spinarak", "Ariados", "Crobat", "Chinchou", "Lanturn", "Pichu", "Cleffa", "Igglybuff", "Togepi", "Togetic", "Natu", "Xatu",
    "Mareep", "Flaaffy", "Ampharos", "Bellossom", "Marrill", "Azumarill", "Sudowoodo", "Politoed", "Hoppip", "Skiploom",
    "Jumpluff ", "Aipom", "Sunkern", "Sunflora", "Yanma", "Wooper", "Quagsire", "Espeon", "Umbreon", "Murkrow", "Slowking",
    "Misdreavus", "Unown", "Wobbuffet", "Girafarig", "Pineco", "Forretress", "Dunsparce", "Gilgar", "Steelix", "Snubbull",
    "Granbull", "Qwilfish", "Scizor", "Shuckle", "Heracross", "Snesael", "Teddiursa", "Ursaring", "Slugma", "Magcargo", "Swinub",
    "Piloswine", "Corsola", "Remoraid", "Octillery", "Delibird", "Mantine", "Skarmory", "Houndour", "Houndoom", "Kingdra",
    "Phanpy", "Donphan", "Porygon", "Stantler", "Smeargle", "Tyrogue", "Hitmontop", "Smoochum", "Elekid", "Magby", "Miltank", "Blissey",
    "Raikou", "Entei", "Suicune", "Larvitar", "Pupitar", "Tyranitar", "Lugia", "Ho-oh", "Celebi", "Treecko", "Grovyle", "Sceptile",
    "Torchic", "Combusken", "Blaziken", "Mudkip", "Marshtomp", "Swampert", "Poochyena", "Mightyena", "Zigzagoon", "Linoone",
    "Wurmple", "Silcoon", "Beautifly", "Cascoon", "Dustox", "Lotad", "Lombre", "Ludicolo", "Seedot", "Nuzleaf", "Shiftry",
    "Taillow", "Swellow", "Wingull", "Pelipper", "Ralts", "Kirlia", "Gardevoir", "Surskit", "Masquerain", "Shroomish", "Breloom",
    "Slakoth", "Vigoroth", "Slaking", "Nincada", "Ninjask", "Shedinja", "Whismur", "Loudred", "Exploud", "Makuhita", "Hariyama",
    "Azurill", "Nosepass", "Skitty", "Delcatty", "Sableye", "Mawlie", "Aron", "Lairon", "Aggron", "Meditite", "Medicham",
    "Electrike", "Manectric", "Plusle", "Minun", "Volbeat", "Illumise", "Roselia", "Gulpin", "Swalot", "Carvanha", "Sharpedo",
    "Wailmer", "Wailord", "Numel", "Camerupt", "Torkoal", "Spoink", "Grumpig", "Spinda", "Trapinch", "Vibrava", "Flygon",
    "Cacnea", "Cacturne", "Swablu", "Altaria", "Zangoose", "Serviper", "Lunatone", "Solrock", "Barbroach", "Whiscash", "Corphish",
    "Crawdaunt", "Baltoy", "Claydol", "Lileep", "Cradily", "Anorith", "Armaldo", "Feebas", "Milotic", "Castform", "Kecleon",
    "Shuppet", "Banette", "Duskull", "Dusclops", "Tropiu­­­­s", "Chimecho", "Absol", "Wynaut", "Snorunt", "Glalie", "Spheal", "Sealeo",
    "Walrein", "Clampearl", "Huntail", "Gorebyss", "Relicanth", "Luvdisc", "Bagon", "Shelgon", "Salamence", "Beldum", "Metang",
    "Metagross", "Regirock", "Regice", "Registeel", "Latias", "Latios", "Kyogre", "Groudon", "Rayquaza", "Jirachi", "Deoxys",
    "Turtwig", "Grotle", "Torterra", "Chimchar", "Monferno", "Infernape", "Piplup", "Prinplup", "Empoleon", "Starly",
    "Staravia", "Staraptor", "Bidoof", "Bibarel", "Kricketot", "Kricketune", "Shinx", "Luxio", "Luxray", "Budew",
    "Roserade", "Cranidos", "Rampardos", "Shieldon", "Bastiodon", "Burmy", "Wormadam", "Mothim", "Combee", "Vespiquen",
    "Pachirisu", "Buizel", "Floatzel", "Cherubi", "Cherrim", "Shellos ", "Gastrodon", "Ambipom", "Drifloon", "Drifblim",
    "Buneary", "Lopunny", "Mismagius", "Honchkrow", "Glameow", "Purugly", "Chingling", "Stunky", "Skuntank", "Bronzor",
    "Bronzong", "Bonsly", "Mime Jr.", "Happiny", "Chatot", "Spiritomb", "Gible", "Gabite", "Garchomp", "Munchlax", "Riolu",
    "Lucario", "Hippopotas", "Hippowdon", "Skorupi", "Drapion", "Crogunk", "Toxicroak", "Carnivine", "Finneon", "Lumineon",
    "Mantyke", "Snover", "Abomasnow", "Weavile", "Magnezone", "Lickilicky", "Rhyperior", "Tangrowth", "Electivire", "Magmortar",
    "Togekiss", "Yanmega", "Leafeon", "Glaceon", "Gliscor", "Mamoswine", "Porygon-Z", "Gallade", "Probopass", "Dusknoir", "Froslass",
    "Rotom", "Uxie", "Mesprit", "Azelf", "Dialga", "Palkia", "Heatran", "Regigigas", "Giratina", "Cresselia", "Phione", "Manaphy ",
    "Darkrai", "Shaymin", "Arceus", "Victini", "Snivy", "Servine", "Serperior", "Tepig", "Pignite", "Emboar", "Oshawott", "Dewott",
    "Samurott", "Patrat", "Watchhog", "Lillipup", "Herdier", "Stoutland", "Purrloin", "Liepard", "Pansage", "Simisage",
    "Pansear", "Simisear", "Panpour", "Simipour", "Munna", "Musharna", "Pidove", "Tranquill", "Unfezant", "Blitzle",
    "Zebstrika", "Roggenrola", "Boldore", "Gigalith", "Woobat", "Swoobat", "Drilbur", "Excadrill", "Audino", "Timburr",
    "Gurdurr", "Conkeldurr", "Tympole", "Palpitoad", "Seismitoad", "Throh", "Sawk", "Sewaddle", "Swadloon", "Leavanny",
    "Venipede", "Whirlipede", "Scolipede", "Cottonee", "Whimsicott", "Petilil", "Lilligant", "Basculin", "Sandile",
    "Krokorok", "Krookodile", "Darumaka", "Darmanitan", "Maractus", "Dwebble", "Crustle", "Scraggy", "Scrafty", "Sigilyph",
    "Yamask", "Cofagrigus", "Tirtouga", "Carracosta", "Archen", "Archeops", "Trubbish", "Garbodor", "Zorua", "Zoroark",
    "Minccino", "Cinccino", "Gothita", "Gothorita", "Gothitelle", "Solosis", "Duosion", "Reuniclus", "Ducklett", "Swanna",
    "Vanillite", "Vanillish", "Vanilluxe", "Deerling", "Sawsbuck", "Emolga", "Karrablast", "Escavalier", "Foongus", "Amoonguss",
    "Frillish", "Jellicent", "Alomomola", "Joltik", "Galvantula", "Ferroseed", "Ferrothorn", "Klink", "Klang", "Klinklang",
    "Tynamo", "Eelektrik", "Eelektross", "Elgyem", "Beheeyem", "Litwik", "Lampent", "Chandelure", "Axew", "Fraxure", "Haxorus",
    "Cubchoo", "Beartic", "Cryogonal", "Shelmet", "Accelgor", "Stunfisk", "Mienfoo", "Mienshao", "Druddigon", "Golett", "Golurk",
    "Pawniard", "Bisharp", "Bouffalant", "Rufflet", "Braviary", "Vullaby", "Mandibuzz", "Heatmor", "Durant", "Deino", "Zweilous",
    "Hydreigon", "Larvesta", "Volcarona", "Cobalion", "Terrakion", "Virizion", "Tornadus", "Thundurus", "Reshiram", "Zekrom",
    "Landorus", "Kyurem", "Keldeo", "Meloetta", "Genesect", "Chespin", "Quilladin", "Chesnaught", "Fennekin", "Braixen", "Delphox",
    "Froakie", "Frogadier", "Greninja", "Bunnelby", "Diggersby", "Fletchling", "Fletchinder", "Talonflame", "Scatterbug", "Spewpa",
    "Vivillon", "Litleo", "Pyroar", "Flabebe", "Floette", "Florges", "Skiddo", "Gogoat", "Pancham", "Pangoro", "Furfrou", "Espurr",
    "Meowstic", "Honedge", "Doublade", "Aegislash", "Spritzee", "Aromatisse", "Swirlix", "Slurpuff", "Inkay", "Malamar", "Binacle",
    "Barbacle", "Skrelp", "Dragalge", "Clauncher", "Clawitzer", "Helioptile", "Heliolisk", "Tyrunt", "Tyrantrum", "Amaura", "Aurorus",
    "Sylveon", "Hawlucha", "Dedenne", "Carbink", "Goomy", "Sliggoo", "Goodra", "Klefki", "Phantump", "Trevenant", "Pumpkaboo",
    "Gourgeist", "Bergmite", "Avalugg", "Noibat", "Noivern", "Xerneas", "Yveltal", "Zygarde", "Diancie", "Volcanion", "Hoopa",
    "Rowlet", "Dartrix", "Decidueye", "Litten", "Torracat", "Incineroar", "Popplio", "Brionne", "Primarina", "Pikipek", "Trumbeak",
    "Toucannon", "Yungoos", "Gumshoos", "Grubbin", "Charjabug", "Vikavolt", "Crabrawler", "Crabominable", "Oricorio", "Cutiefly",
    "Ribombee", "Rockruff", "Lycanroc", "Wishiwashi", "Mareanie", "Toxapex", "Mudbray", "Mudsdale", "Dewpider", "Araquanid",
    "Fomantis", "Lurantis", "Morelull", "Shiinotic", "Salandit", "Salazzle", "Stufful", "Bewear", "Bounsweet", "Steenee",
    "Tsareena", "Comfey", "Oranguru", "Passimian", "Wimpod", "Golisopod", "Sandygast", "Palossand", "Pyukumuku", "Type: Null",
    "Silvally", "Minior", "Komala", "Turtonator", "Togedemaru", "Mimikyu", "Bruxish", "Drampa", "Dhelmise", "Jangmo-o",
    "Hakamo-o", "Kommo-o", "Tapu Koko", "Tapu Lele", "Tapu Bulu", "Tapu Fini", "Cosmog", "Cosmoem", "Solgaleo", "Lunala",
    "Nihilgo", "Buzzwole", "Pheromosa", "Xurkitree", "Celesteela", "Kartana", "Guzzlord", "Necrozma", "Magearna", "Marshadow"]

pokeblacklist = ["vore", "sexually_suggestive", "mouthshot", "piss", "pee", "scat", "flash",
    "watersports", "nude", "comic", "diaper", "foot_focus", "panties", "pregnant",
    "pokeshaming", "urine", "fat", "inflation", "huge_breasts", "overweight", "pokemorph",
    "hyper_hips", "hyper_breasts", "huge_hips", "huge_butt", "hyper_butt", "topless",
    "underwear", "blood", "bleeding", "knife", "big_breasts", "tight_clothing", "group",
    "tears", "bondage"]

dabtype = ["it's not fucking 2011, what the hell..",
    "is this hell?",
    "uhh.. please end my suffering.",
    "what the fuck nagger?",
    "use nsfw roleplay commands instead, please.",
    "why though?"]

braixencomments = ["Aaaaaaaaaaa, it's so cute",
    "i want to cuddle it <3",
    "go hug it now, aaaa <3",
    "it's so fluffy!!!!",
    "oh my god, how cute can it be?!",
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "why arent braixens real? :(",
    "look at it! it wants a hug from you~",
    "there's never enough braixen~ <3"]

subjekti = ["A dude", "My mom", "My gay son", "Some guy", "A random lad",
    "Yo mama", "A cute Braixen", "My girlfriend", "Apustaja", "PewDiePie",
    "Viheraho", "Markiplier", "Niilo22", "A CS:GO scammer", "Rulettaja", "MrLadu",
    "The son you aren't proud of", "LatisChips", "Favor", "Peteksi", "Mokkapala",
    "Jacksfilms", "Gene from the Emoji Movie", "Jailbreak from the Emoji Movie",
    "Your gay stepdad", "Some randy in a closet", "Jake Paul", "The Disney Channel crew",
    "A nice person", "JorgeVlogs", "Jusu", "Lakkofani05", "A [redacted N word]",
    "jaqreven", "a Lucario", "a Lycanroc", "a Fennekin", "Karma"]

predikaatti = ["eats", "licks", "spies on", "treats", "meets up with", "fucks",
    "hacks", "configures", "spies on", "feeds", "meows on", "flees from",
    "tries to automate", "explodes", "spits on", "cooks", "crawls on",
    "had sex with", "fapped to", "wants to fuck", "really wants to hug",
    "is having a great time with", "is getting kissed by", "is looking up to",
    "is cuddling", "punches", "licks", "kisses", "hugs", "cuddles with"]

objekti = ["your mom", "themselves", "a Samsung Galaxy Note 7", "a bottle of Suomiviina",
    "me", "my best friend", "a [redacted N word]", "LatisChips",
    "Niilo22", "Viheraho", "the Emoji Movie", "the Minions Banana baby", "a Braixen",
    "a random guy with a knife", "yo mama", "an angel", "a rabbit", "Minecraft Steve",
    "a random cube making Roblox ""oof"" noises", "all the bad consoles", "rabbit stew",
    "Jusu's moped car", "a Lucario", "Habboilianskype", "Lakkofani05", "Jake Paul",
    "jaqreven", "a Lycanroc", "a random hobo", "my mom", "Karma"]

adverbi = ["to make a pie", "for no apparent reason", "because the sky is green",
    "for a disease", "to be able to make toast explode", "to learn about interest rates",
    "to skip school", "to die quickly in 5 SIMPLE STEPS! LEARN MORE NOW",
    "to reconsider the value of life", "because they can", "for your mom",
    "to get out of jail", "to find a cake", "to get a life", "because life is cool",
    "to learn more about the furry fandom", "to make up a dank meme",
    "because they're gay", "because they are feeling happy", "because of you"]
